export interface DashboardType {
  id: string;
  userId: string;
  diagnosisYear: number;
  diagnosisMethod: string;
  incidenceDate: string;
  mortalityDate: string | null;
  cieOTopographicCode: string;
  cieOTopographicName: string;
  cieOMorphologicCode: string;
  cieOMorphologicName: string;
  cie10Code: string;
  cie10Name: string;
  behavior: string;
  tumorState: string;
  multiple: boolean;
  deathCertificateNumber?: string;
  registeredCauseOfDeath?: string;
  documentType: string;
  documentNumber: string;
  firstName: string;
  secondName: string | null;
  lastName: string;
  secondLastName: string | null;
  sex: string;
  age: number;
  ageUnit: string;
  municipality: string;
  subregion: string;
  address: string;
}
